# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[directory]
truncate_to_repo = false
truncation_length = 100

[aws]
style = "bold blue"
symbol = "aws"

[aws.region_aliases]
ap-northeast-1 = "jp"
us-east-1 = "va"
