###
# LSP
###

# LSP settings
[[plugins]]
hook_add = '''
command LSP LspManageServers
" Leader fmでフォーマット
nnoremap <Leader>fm <cmd>LspDocumentFormat<cr>
" 保存時自動フォーマット
autocmd BufWritePre <buffer> LspDocumentFormatSync
" 補完表示時のEnterで改行をしない
inoremap <expr><CR>  pumvisible() ? "<C-y>" : "<CR>"
set completeopt=menuone,noinsert
inoremap <expr><C-n> pumvisible() ? "<Down>" : "<C-n>"
inoremap <expr><C-p> pumvisible() ? "<Up>" : "<C-p>"
'''
repo = 'mattn/vim-lsp-settings'

###
# Theme
###


[[plugins]] # カラースキーマ
hook_add = '''
  set termguicolors
  " the configuration options should be placed before `colorscheme sonokai`
  if has('termguicolors')
    set termguicolors
  endif

  " The configuration options should be placed before `colorscheme sonokai`.
  let g:sonokai_style = 'andromeda'
  let g:sonokai_enable_italic = 1
  let g:sonokai_disable_italic_comment = 1
  let g:sonokai_transparent_background = 1
  colorscheme sonokai
'''
repo = 'sainnhe/sonokai'

