[[plugins]]
build = 'sh -c "cd app & yarn install" '
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
repo = 'iamcco/markdown-preview.nvim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
hook_add = '''
nnoremap qf :Qfreplace<CR>
'''
repo = 'thinca/vim-qfreplace'

[[plugins]]
hook_add = '''
nnoremap <silent> <leader>gg :LazyGit<CR>
let g:lazygit_use_neovim_remote = 0
'''
repo = 'kdheepak/lazygit.nvim'
